%  Auto-generated by MATLAB on 01-Dec-2018 18:26:33

% Create figure
figure1 = figure('NumberTitle','off','Name','Espectro de envelope');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
L = length(ext.acc);
f = (0:L/2)*(Fs/L);
plot(f,envspectrum(ext.acc,Fs));

% Create ylabel
ylabel('Acelera\c{c}\~ao $\rm [m/s^2]$','Interpreter','latex');

% Create xlabel
xlabel('Frequ\^encia $\rm [Hz]$','Interpreter','latex');

xlim(axes1,[0 600]);
ylim(axes1,[0 25]);
box(axes1,'on');
% Create textarrow
annotation(figure1,'textarrow',[0.3057 0.2686],...
    [0.7419 0.6150],'String',{'$1\times BPFO$'},...
    'Interpreter','latex');

% Create textarrow
annotation(figure1,'textarrow',[0.4443 0.4071],...
    [0.8247 0.7019],'String',{'$2\times BPFO$'},...
    'Interpreter','latex');

% Create textarrow
annotation(figure1,'textarrow',[0.5961 0.5457],...
    [0.8247 0.714],'String',{'$3\times BPFO$'},...
    'Interpreter','latex');
