%  Auto-generated by MATLAB on 01-Dec-2018 18:08:34

% Create figure
figure1 = figure('NumberTitle','off','Name','Espectro de frequencias');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
Y = fft(ext.acc);
L = length(ext.acc);
f = (0:L/2)*(Fs/L);
P2 = abs(Y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2*P1(2:end-1);
plot(f,P1);

% Create ylabel
ylabel('Acelera\c{c}\~ao $\rm [m/s^2]$','Interpreter','latex');

% Create xlabel
xlabel('Frequ\^encia $\rm [Hz]$','Interpreter','latex');

xlim(axes1,[0 10000]);
box(axes1,'on');
% Create textarrow
annotation(figure1,'textarrow',[0.4589 0.5318],...
    [0.7976 0.8471],...
    'String',{'$\mathit{f}\approx\omega_{no}$'},...
    'Interpreter','latex',...
    'FontSize',14);
