%  Auto-generated by MATLAB on 01-Dec-2018 17:43:02

% Create figure
figure1 = figure('NumberTitle','off','Name','Deslocamento anel externo');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(t,ext.pos);

% Create ylabel
ylabel('Deslocamento $\rm [m]$','Interpreter','latex');

% Create xlabel
xlabel('Tempo $\rm [s]$','Interpreter','latex');

xlim(axes1,[0 0.1]);
ylim(axes1,[-3e-06 4e-06]);
box(axes1,'on');
% Create line
annotation(figure1,'line',[0.276 0.276],[0.757 0.876]);

% Create line
annotation(figure1,'line',[0.346 0.346],[0.757 0.876]);

% Create arrow
annotation(figure1,'arrow',[0.2075 0.2718],[0.844 0.844]);

% Create textbox
annotation(figure1,'textbox',...
    [0.3675 0.845 0.1280 0.06190],...
    'String',{'1/BPFO'},...
    'LineStyle','none',...
    'Interpreter','latex',...
    'FitBoxToText','off',...
    'FontSize',12);

% Create arrow
annotation(figure1,'arrow',[0.49 0.3475],[0.844 0.844]);